from __future__ import annotations

import json
from datetime import datetime, timezone
from io import BytesIO
from zipfile import ZipFile

from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.db.base import Base as CoreBase
from app.db.models import TrustEvent, User
from app.services.evidence_pack_service import (
    DEFAULT_FOOTER,
    LIMITATION_STATEMENT,
    PROTOCOL_VERSION,
    build_evidence_pack_meta,
    build_evidence_pack_zip,
)


def _session():
    engine = create_engine(
        "sqlite+pysqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
        future=True,
    )
    CoreBase.metadata.create_all(bind=engine)
    SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, future=True)
    return engine, SessionLocal()


def test_evidence_pack_meta_faces_users_as_gsn():
    engine, db = _session()
    try:
        user = User(
            id=7,
            email="evidence@example.com",
            hashed_password="x",
            role="user",
            gmfn_id="GSN-USER-7",
        )
        meta = build_evidence_pack_meta(db, current_user=user)

        assert meta["pack_id"].startswith("GSN-PACK-U7-STANDARD-")
        assert meta["title"] == "GSN Evidence Pack"
        assert meta["surface_brand"] == "GSN"
        assert meta["surface_brand_full"] == "Global Support Network"
        assert meta["protocol_version"] == PROTOCOL_VERSION
        assert meta["footer"] == DEFAULT_FOOTER
        assert meta["limitation_statement"] == LIMITATION_STATEMENT
    finally:
        db.close()
        engine.dispose()


def test_evidence_pack_meta_route_uses_gsn_package_contract(
    client: TestClient,
    override_current_user_user,
    seed_clan_member_membership,
):
    response = client.get("/trust/me/evidence-pack/meta")

    assert response.status_code == 200, response.text
    meta = response.json()
    assert meta["pack_id"].startswith("GSN-PACK-U1-STANDARD-")
    assert not meta["pack_id"].startswith("TP-U")
    assert meta["title"] == "GSN Evidence Pack"
    assert meta["surface_brand"] == "GSN"
    assert meta["protocol_version"] == PROTOCOL_VERSION
    assert meta["merchant_visibility_level"] == "standard"
    assert meta["evidence_alignment"] == "trustslip_visibility_bound"


def test_evidence_pack_zip_contains_gsn_manifest_readme_and_checksums():
    engine, db = _session()
    try:
        user = User(
            id=9,
            email="pack@example.com",
            hashed_password="x",
            role="user",
            gmfn_id="GSN-USER-9",
        )
        db.add(user)
        db.commit()
        db.refresh(user)

        zip_bytes = build_evidence_pack_zip(
            db,
            current_user=user,
            trustslip_summary={
                "code": "TS-GSN-9",
                "status": "active",
                "currency": "NGN",
                "trust_limit": "100.00",
                "cci_score": "71",
                "cci_band": "B",
            },
        )

        with ZipFile(BytesIO(zip_bytes), "r") as zf:
            names = set(zf.namelist())
            assert {"manifest.json", "trustslip_snapshot.json", "README.txt", "checksums.json"}.issubset(names)

            manifest = json.loads(zf.read("manifest.json").decode("utf-8"))
            readme = zf.read("README.txt").decode("utf-8")
            snapshot_text = zf.read("trustslip_snapshot.json").decode("utf-8")
            snapshot = json.loads(snapshot_text)
            checksums = json.loads(zf.read("checksums.json").decode("utf-8"))

        assert manifest["pack_id"].startswith("GSN-PACK-U9-STANDARD-")
        assert manifest["title"] == "GSN Evidence Pack"
        assert manifest["surface_brand"] == "GSN"
        assert manifest["document_type"] == "portable_trust_evidence_package"
        assert "Generated by GSN" in manifest["authority_note"]
        assert manifest["limitation_statement"] == LIMITATION_STATEMENT
        assert manifest["holder"]["gsn_id"] == "GSN-USER-9"
        assert manifest["holder"]["private_contact_details"] == "redacted for portable evidence pack"
        assert "user" not in manifest
        assert "user_id" not in json.dumps(manifest)
        assert "email" not in json.dumps(manifest)
        assert "phone_e164" not in json.dumps(manifest)
        assert "GSN Evidence Pack" in readme
        assert "GMFN Evidence Pack" not in readme
        assert LIMITATION_STATEMENT in readme
        assert "Privacy note:" in readme
        assert "complete TrustSlip internals" in readme
        assert "full_summary" not in snapshot
        assert "full_summary" not in snapshot_text
        assert snapshot["private_summary_boundary"].startswith("This portable pack uses")
        assert checksums["checksums"]["manifest.json"]
        assert checksums["checksums"]["trustslip_snapshot.json"]
    finally:
        db.close()
        engine.dispose()


def test_evidence_pack_zip_redacts_recent_event_operational_references():
    engine, db = _session()
    try:
        user = User(
            id=10,
            email="pack-redacted@example.com",
            hashed_password="x",
            role="user",
            gmfn_id="GSN-USER-10",
        )
        db.add(user)
        db.add(
            TrustEvent(
                event_type="loan.repaid",
                clan_id=3,
                loan_id=77,
                guarantor_id=44,
                actor_user_id=9,
                subject_user_id=10,
                meta={
                    "reason": "loan_fully_repaid",
                    "note": "Settlement confirmed",
                    "payment_reference": "PRIVATE-PACK-REF-001",
                },
                created_at=datetime.now(timezone.utc),
            )
        )
        db.commit()
        db.refresh(user)

        zip_bytes = build_evidence_pack_zip(
            db,
            current_user=user,
            trustslip_summary={
                "code": "TS-GSN-10",
                "status": "active",
                "currency": "NGN",
                "trust_limit": "100.00",
                "cci_score": "71",
                "cci_band": "B",
            },
        )

        with ZipFile(BytesIO(zip_bytes), "r") as zf:
            snapshot_text = zf.read("trustslip_snapshot.json").decode("utf-8")
            snapshot = json.loads(snapshot_text)

        assert snapshot["recent_events"]
        event = snapshot["recent_events"][0]
        assert event["reference_label"] == "Private support record"
        assert "payment_reference" not in event
        assert "loan_id" not in event
        assert "clan_id" not in event
        assert "guarantor_id" not in event
        assert "actor_user_id" not in event
        assert "subject_user_id" not in event
        assert "meta" not in event
        assert "PRIVATE-PACK-REF-001" not in snapshot_text
    finally:
        db.close()
        engine.dispose()
