"""add loan_guarantors

Revision ID: 7676f3a858a7
Revises: 7ef178208e20
Create Date: 2026-01-07 12:45:27.305454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7676f3a858a7'
down_revision: Union[str, Sequence[str], None] = '7ef178208e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- create loan_guarantors table (new table = safe on SQLite) ---
    
    with op.batch_alter_table("clan_memberships") as batch_op:
        batch_op.create_unique_constraint("uq_clan_membership", ["clan_id", "user_id"])

    # Add loans.guarantors_required safely (if it doesn't already exist)
    with op.batch_alter_table("loans") as batch_op:
        batch_op.add_column(sa.Column("guarantors_required", sa.Integer(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'clan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'borrower_user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('loans', 'guarantors_required')
    op.drop_constraint(None, 'clan_memberships', type_='foreignkey')
    op.drop_constraint(None, 'clan_memberships', type_='foreignkey')
    op.drop_constraint('uq_clan_membership', 'clan_memberships', type_='unique')
    op.drop_index(op.f('ix_loan_guarantors_loan_id'), table_name='loan_guarantors')
    op.drop_index(op.f('ix_loan_guarantors_id'), table_name='loan_guarantors')
    op.drop_index(op.f('ix_loan_guarantors_guarantor_user_id'), table_name='loan_guarantors')
    op.drop_index(op.f('ix_loan_guarantors_clan_id'), table_name='loan_guarantors')
    op.drop_table('loan_guarantors')
    # ### end Alembic commands ###
