"""add clans and clan memberships and clan_id on loans

Revision ID: 7ef178208e20
Revises: 27ea7c97743a
Create Date: 2026-01-06 17:38:16.534300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef178208e20'
down_revision: Union[str, Sequence[str], None] = '27ea7c97743a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_memberships_clan_id'), 'clan_memberships', ['clan_id'], unique=False)
    op.create_index(op.f('ix_clan_memberships_id'), 'clan_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_clan_memberships_user_id'), 'clan_memberships', ['user_id'], unique=False)
    op.create_table('clans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clans_id'), 'clans', ['id'], unique=False)
    op.create_index(op.f('ix_clans_name'), 'clans', ['name'], unique=True)
    op.add_column('loans', sa.Column('clan_id', sa.Integer(), nullable=True)) 
    op.create_index(op.f('ix_loans_clan_id'), 'loans', ['clan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_clan_id'), table_name='loans')
    op.drop_column('loans', 'clan_id')
    op.drop_index(op.f('ix_clans_name'), table_name='clans')
    op.drop_index(op.f('ix_clans_id'), table_name='clans')
    op.drop_table('clans')
    op.drop_index(op.f('ix_clan_memberships_user_id'), table_name='clan_memberships')
    op.drop_index(op.f('ix_clan_memberships_id'), table_name='clan_memberships')
    op.drop_index(op.f('ix_clan_memberships_clan_id'), table_name='clan_memberships')
    op.drop_table('clan_memberships')
    # ### end Alembic commands ###
