"""add personal pool balance

Revision ID: e2ae44a31eb1
Revises: 7676f3a858a7
Create Date: 2026-01-07 16:20:39.165640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ae44a31eb1'
down_revision: Union[str, Sequence[str], None] = '7676f3a858a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("clan_memberships") as batch_op:
        batch_op.add_column(
            sa.Column(
                "personal_pool_balance",
                sa.Numeric(12, 2),
                server_default="0",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'clan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loans', 'borrower_user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'clan_memberships', type_='foreignkey')
    op.drop_constraint(None, 'clan_memberships', type_='foreignkey')
    # ### end Alembic commands ###
